name: scheduletest
on:
  schedule:
    - cron:  '49 */1 * * *'

jobs:
  # audit
  audit:
    name: audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm i
    - run: npm audit
# Todo Test
