name: scheduletest
on:
  schedule:
    - cron:  '46 */1 * * *'
    - branches:
      - githubactions

jobs:
  # audit
  audit:
    name: audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm i
    - run: npm audit
# Todo Test
